# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\nd1.storage\"M\n\x0cStoreRequest\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x12\x17\n\x0f\x61ssociated_data\x18\x02 \x01(\x0c\x12\x11\n\tgroup_ids\x18\x03 \x03(\t\"\"\n\rStoreResponse\x12\x11\n\tobject_id\x18\x01 \x01(\t\"$\n\x0fRetrieveRequest\x12\x11\n\tobject_id\x18\x01 \x01(\t\">\n\x10RetrieveResponse\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x12\x17\n\x0f\x61ssociated_data\x18\x02 \x01(\x0c\"N\n\rUpdateRequest\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x12\x17\n\x0f\x61ssociated_data\x18\x02 \x01(\x0c\x12\x11\n\tobject_id\x18\x03 \x01(\t\"\x10\n\x0eUpdateResponse\"\"\n\rDeleteRequest\x12\x11\n\tobject_id\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65leteResponse2\x98\x02\n\x07Storage\x12>\n\x05Store\x12\x18.d1.storage.StoreRequest\x1a\x19.d1.storage.StoreResponse\"\x00\x12G\n\x08Retrieve\x12\x1b.d1.storage.RetrieveRequest\x1a\x1c.d1.storage.RetrieveResponse\"\x00\x12\x41\n\x06Update\x12\x19.d1.storage.UpdateRequest\x1a\x1a.d1.storage.UpdateResponse\"\x00\x12\x41\n\x06\x44\x65lete\x12\x19.d1.storage.DeleteRequest\x1a\x1a.d1.storage.DeleteResponse\"\x00\x42\x99\x01\n!io.cybercrypt.d1.protobuf.storageB\x0cStorageProtoZ>github.com/cybercryptio/d1-service-storage/v2/protobuf/storage\xaa\x02%CyberCrypt.D1.Client.Protobuf.Storageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!io.cybercrypt.d1.protobuf.storageB\014StorageProtoZ>github.com/cybercryptio/d1-service-storage/v2/protobuf/storage\252\002%CyberCrypt.D1.Client.Protobuf.Storage'
  _STOREREQUEST._serialized_start=29
  _STOREREQUEST._serialized_end=106
  _STORERESPONSE._serialized_start=108
  _STORERESPONSE._serialized_end=142
  _RETRIEVEREQUEST._serialized_start=144
  _RETRIEVEREQUEST._serialized_end=180
  _RETRIEVERESPONSE._serialized_start=182
  _RETRIEVERESPONSE._serialized_end=244
  _UPDATEREQUEST._serialized_start=246
  _UPDATEREQUEST._serialized_end=324
  _UPDATERESPONSE._serialized_start=326
  _UPDATERESPONSE._serialized_end=342
  _DELETEREQUEST._serialized_start=344
  _DELETEREQUEST._serialized_end=378
  _DELETERESPONSE._serialized_start=380
  _DELETERESPONSE._serialized_end=396
  _STORAGE._serialized_start=399
  _STORAGE._serialized_end=679
# @@protoc_insertion_point(module_scope)
