# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authn.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import scopes_pb2 as scopes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61uthn.proto\x12\x08\x64\x31.authn\x1a\x0cscopes.proto\"5\n\x11\x43reateUserRequest\x12 \n\x06scopes\x18\x01 \x03(\x0e\x32\x10.d1.scopes.Scope\"7\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x10LoginUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\">\n\x11LoginUserResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x13\n\x0b\x65xpiry_time\x18\x02 \x01(\x03\"$\n\x11RemoveUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x14\n\x12RemoveUserResponse\"6\n\x12\x43reateGroupRequest\x12 \n\x06scopes\x18\x01 \x03(\x0e\x32\x10.d1.scopes.Scope\"\'\n\x13\x43reateGroupResponse\x12\x10\n\x08group_id\x18\x01 \x01(\t\"<\n\x16\x41\x64\x64UserToGroupsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tgroup_ids\x18\x02 \x03(\t\"\x19\n\x17\x41\x64\x64UserToGroupsResponse\"A\n\x1bRemoveUserFromGroupsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tgroup_ids\x18\x02 \x03(\t\"\x1e\n\x1cRemoveUserFromGroupsResponse2\xf6\x03\n\x05\x41uthn\x12I\n\nCreateUser\x12\x1b.d1.authn.CreateUserRequest\x1a\x1c.d1.authn.CreateUserResponse\"\x00\x12\x46\n\tLoginUser\x12\x1a.d1.authn.LoginUserRequest\x1a\x1b.d1.authn.LoginUserResponse\"\x00\x12I\n\nRemoveUser\x12\x1b.d1.authn.RemoveUserRequest\x1a\x1c.d1.authn.RemoveUserResponse\"\x00\x12L\n\x0b\x43reateGroup\x12\x1c.d1.authn.CreateGroupRequest\x1a\x1d.d1.authn.CreateGroupResponse\"\x00\x12X\n\x0f\x41\x64\x64UserToGroups\x12 .d1.authn.AddUserToGroupsRequest\x1a!.d1.authn.AddUserToGroupsResponse\"\x00\x12g\n\x14RemoveUserFromGroups\x12%.d1.authn.RemoveUserFromGroupsRequest\x1a&.d1.authn.RemoveUserFromGroupsResponse\"\x00\x42\x91\x01\n\x1fio.cybercrypt.d1.protobuf.authnB\nAuthnProtoZ<github.com/cybercryptio/d1-service-generic/v2/protobuf/authn\xaa\x02#CyberCrypt.D1.Client.Protobuf.Authnb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authn_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.cybercrypt.d1.protobuf.authnB\nAuthnProtoZ<github.com/cybercryptio/d1-service-generic/v2/protobuf/authn\252\002#CyberCrypt.D1.Client.Protobuf.Authn'
  _CREATEUSERREQUEST._serialized_start=39
  _CREATEUSERREQUEST._serialized_end=92
  _CREATEUSERRESPONSE._serialized_start=94
  _CREATEUSERRESPONSE._serialized_end=149
  _LOGINUSERREQUEST._serialized_start=151
  _LOGINUSERREQUEST._serialized_end=204
  _LOGINUSERRESPONSE._serialized_start=206
  _LOGINUSERRESPONSE._serialized_end=268
  _REMOVEUSERREQUEST._serialized_start=270
  _REMOVEUSERREQUEST._serialized_end=306
  _REMOVEUSERRESPONSE._serialized_start=308
  _REMOVEUSERRESPONSE._serialized_end=328
  _CREATEGROUPREQUEST._serialized_start=330
  _CREATEGROUPREQUEST._serialized_end=384
  _CREATEGROUPRESPONSE._serialized_start=386
  _CREATEGROUPRESPONSE._serialized_end=425
  _ADDUSERTOGROUPSREQUEST._serialized_start=427
  _ADDUSERTOGROUPSREQUEST._serialized_end=487
  _ADDUSERTOGROUPSRESPONSE._serialized_start=489
  _ADDUSERTOGROUPSRESPONSE._serialized_end=514
  _REMOVEUSERFROMGROUPSREQUEST._serialized_start=516
  _REMOVEUSERFROMGROUPSREQUEST._serialized_end=581
  _REMOVEUSERFROMGROUPSRESPONSE._serialized_start=583
  _REMOVEUSERFROMGROUPSRESPONSE._serialized_end=613
  _AUTHN._serialized_start=616
  _AUTHN._serialized_end=1118
# @@protoc_insertion_point(module_scope)
