# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import generic_pb2 as generic__pb2


class GenericStub(object):
    """Service for encryption and decryption of data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encrypt = channel.unary_unary(
                '/d1.generic.Generic/Encrypt',
                request_serializer=generic__pb2.EncryptRequest.SerializeToString,
                response_deserializer=generic__pb2.EncryptResponse.FromString,
                )
        self.Decrypt = channel.unary_unary(
                '/d1.generic.Generic/Decrypt',
                request_serializer=generic__pb2.DecryptRequest.SerializeToString,
                response_deserializer=generic__pb2.DecryptResponse.FromString,
                )


class GenericServicer(object):
    """Service for encryption and decryption of data.
    """

    def Encrypt(self, request, context):
        """Encrypts data and returns the ciphertext without storing it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Authorizes the user for access permissions and if accessible, returns the decrypted content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenericServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=generic__pb2.EncryptRequest.FromString,
                    response_serializer=generic__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=generic__pb2.DecryptRequest.FromString,
                    response_serializer=generic__pb2.DecryptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'd1.generic.Generic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Generic(object):
    """Service for encryption and decryption of data.
    """

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/d1.generic.Generic/Encrypt',
            generic__pb2.EncryptRequest.SerializeToString,
            generic__pb2.EncryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/d1.generic.Generic/Decrypt',
            generic__pb2.DecryptRequest.SerializeToString,
            generic__pb2.DecryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
