# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scopes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscopes.proto\x12\td1.scopes*a\n\x05Scope\x12\x08\n\x04READ\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\r\n\tGETACCESS\x10\x02\x12\x10\n\x0cMODIFYACCESS\x10\x03\x12\n\n\x06UPDATE\x10\x04\x12\n\n\x06\x44\x45LETE\x10\x05\x12\t\n\x05INDEX\x10\x06\x42\x92\x01\n io.cybercrypt.d1.protobuf.scopesB\x0bScopesProtoZ:github.com/cybercryptio/d1-service-generic/protobuf/scopes\xaa\x02$CyberCrypt.D1.Client.Protobuf.Scopesb\x06proto3')

_SCOPE = DESCRIPTOR.enum_types_by_name['Scope']
Scope = enum_type_wrapper.EnumTypeWrapper(_SCOPE)
READ = 0
CREATE = 1
GETACCESS = 2
MODIFYACCESS = 3
UPDATE = 4
DELETE = 5
INDEX = 6


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n io.cybercrypt.d1.protobuf.scopesB\013ScopesProtoZ:github.com/cybercryptio/d1-service-generic/protobuf/scopes\252\002$CyberCrypt.D1.Client.Protobuf.Scopes'
  _SCOPE._serialized_start=27
  _SCOPE._serialized_end=124
# @@protoc_insertion_point(module_scope)
