# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scopes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscopes.proto\x12\td1.scopes*a\n\x05Scope\x12\x08\n\x04READ\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\r\n\tGETACCESS\x10\x02\x12\x10\n\x0cMODIFYACCESS\x10\x03\x12\n\n\x06UPDATE\x10\x04\x12\n\n\x06\x44\x45LETE\x10\x05\x12\t\n\x05INDEX\x10\x06\x42\x95\x01\n io.cybercrypt.d1.protobuf.scopesB\x0bScopesProtoZ=github.com/cybercryptio/d1-service-generic/v2/protobuf/scopes\xaa\x02$CyberCrypt.D1.Client.Protobuf.Scopesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scopes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n io.cybercrypt.d1.protobuf.scopesB\013ScopesProtoZ=github.com/cybercryptio/d1-service-generic/v2/protobuf/scopes\252\002$CyberCrypt.D1.Client.Protobuf.Scopes'
  _SCOPE._serialized_start=27
  _SCOPE._serialized_end=124
# @@protoc_insertion_point(module_scope)
