# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rversion.proto\x12\nd1.version\"\x10\n\x0eVersionRequest\".\n\x0fVersionResponse\x12\x0e\n\x06\x63ommit\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t2O\n\x07Version\x12\x44\n\x07Version\x12\x1a.d1.version.VersionRequest\x1a\x1b.d1.version.VersionResponse\"\x00\x42\x96\x01\n!io.cybercrypt.d1.protobuf.versionB\x0cVersionProtoZ;github.com/cybercryptio/d1-service-generic/protobuf/version\xaa\x02%CyberCrypt.D1.Client.Protobuf.Versionb\x06proto3')



_VERSIONREQUEST = DESCRIPTOR.message_types_by_name['VersionRequest']
_VERSIONRESPONSE = DESCRIPTOR.message_types_by_name['VersionResponse']
VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:d1.version.VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:d1.version.VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)

_VERSION = DESCRIPTOR.services_by_name['Version']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!io.cybercrypt.d1.protobuf.versionB\014VersionProtoZ;github.com/cybercryptio/d1-service-generic/protobuf/version\252\002%CyberCrypt.D1.Client.Protobuf.Version'
  _VERSIONREQUEST._serialized_start=29
  _VERSIONREQUEST._serialized_end=45
  _VERSIONRESPONSE._serialized_start=47
  _VERSIONRESPONSE._serialized_end=93
  _VERSION._serialized_start=95
  _VERSION._serialized_end=174
# @@protoc_insertion_point(module_scope)
